### PR TITLE
allow Pythonic None as checksum

### LINKED ISSUE #11: Pythonic None should be preferred to 'None' in checksum arg for BloscpackArgs
The subject says it all.

### PR DESCRIPTION
**Pull request by esc**
fixes #11 cc @FrancescAlted @FrancescElies

### CODE REVIEW

**Comment by esc** [comment]
a bot hacky, but O.K.

**Comment by FrancescElies** [comment]
Hi @esc 
I had a look to the failing test and this PR did not introduce any new failed tests.
- [Merge Travis CI output](https://travis-ci.org/Blosc/bloscpack/jobs/242803238) 
- [Previous comit](https://travis-ci.org/Blosc/bloscpack/jobs/242572320) 

The traceback
```
Traceback (most recent call last):
  File "/Users/cesc/anaconda/envs/py3/lib/python3.5/site-packages/nose/case.py", line 19
8, in runTest                                                                          
    self.test(*self.arg)
  File "/Users/cesc/src/bloscpack/test/test_headers.py", line 170, in test_decode_blosc_
header                                                                                 
    nt.assert_equal(expected, header)
AssertionError: {'blocksize': 88, 'typesize': 8, 'version[58 chars]: 92} != OrderedDict(
[('version', 2), ('versionlz'[86 chars]08)])                                           
```

I executed them locally, the only parameter not matching are the flags
- expected flag: 3 (0x3)
- header flag: 19 (0x13)

The test sets `blosc_args.shuffle = True` therefore according to [header spec](https://github.com/Blosc/c-blosc/blob/master/README_HEADER.rst) if I understand it correctly the expected flag should be 0x1X.

About X (bit 4 to 7) I'm not sure anymore, we have 0x3 in the header which means is using `zlib`, right? but `blosc_args` value is `Out[8]: BloscArgs(typesize=8, clevel=7, shuffle=True, cname='blosclz') `

Is this a bug, or shall the expected flag in the test be 19 (0x13)?

**Comment by esc** [comment]
It works fine with older versions, 1.2.7 for example. Not exactly sure, but perhaps the header format for blosc has changed? cc @FrancescAlted @aalted

**Comment by FrancescElies** [comment]
If I see correctly `write_compression_header` has changed after that version, now it [ sets dont_split](https://github.com/Blosc/c-blosc/blob/master/blosc/blosc.c#L1140-L1143) and [sets BLOSC_DOSHUFFLE and BLOSC_MEMCPYED](https://github.com/Blosc/c-blosc/blob/master/blosc/blosc.c#L1125-L1133). In the links you can see the lines that are actually setting the flag to 0x13.

**Comment by esc** [comment]
O.K. let's move the discussion to #62 -- if python-blosc is broken, we should a) fix bloscpack and b) limit the minimum version of `python-blosc` via the `requirements.txt` file.

**Pull request merged**
