### PR TITLE
Python 3 Compatability

### PR DESCRIPTION
**Pull request by esc**

### CODE REVIEW

**Comment by esc** [comment]
@aldanor I have attached a bunch of commits to this, if you want to, feel free to test this.

**Comment by esc** [comment]
Still fixing the last bits and bobs, travis tests almost working.

**Comment by aldanor** [comment]
@esc Thanks! will check it out shortly

**Comment by esc** [comment]
ZOMG Travis is finally passing all tests! :+1:

**Comment by mrocklin** [comment]
Everything here seems sane to me.

**Comment by FrancescAlted** [comment]
@esc are you waiting for someone to merge this?  I can give a hand if needed :)

**Comment by esc** [comment]
No, there are still a few things nagging and not done right. When dealing with dataformats, it is better to get it right rather than pay the high price of making a silly mistake.

**Comment by esc** [comment]
There are still a few things nagging me here. I'll post them as they come to mind.

First:

61392e1fd61e48682df2efe81e891e0acdb1eaca

I think the encode and decode of the metadata should not be the resonsibility of the metacodec(which is a really silly name) and in Python 3 we should handle metadata encode-decode outside. Imagine someone used the metacodec to encode-decode binary, it may crash when deserializing during an attempt to turn it into unicode.

thoughts.

**Comment by esc** [comment]
I rebased it now that it converts it in a different place. The assumption here is that the caller should receive a 1-1 compatible codec and zlib only accpets bytes in Python 3 (and so should we).

**Comment by esc** [comment]
Darn, same issue for hashes.

**Comment by esc** [comment]
Hashes have been resolved also.

**Comment by esc** [comment]
Alright, it is going in.

**Comment by aldanor** [comment]
Everything seems good so far, thanks @esc!

**Comment by esc** [comment]
new release coming soon.

**Pull request merged**
