### PR TITLE
fixes test & splits test in 3 tests

### LINKED ISSUE #62: Tests currently broken
```
\Traceback (most recent call last):
  File "/home/esc/git/bloscpack/test-venv/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/esc/git/bloscpack/test/test_headers.py", line 168, in test_decode_blosc_header
    nt.assert_equal(expected, header)
AssertionError: {'flags': 3, 'blocksize': 88, 'typesize':[58 chars] 108} != OrderedDict([('version', 2), ('versionlz'[86 chars]08)])
```

On master.

### PR DESCRIPTION
**Pull request by FrancescElies**
fixes #62 and splits test in three tests. What do you think?

### CODE REVIEW

**Comment by esc** [comment]
This looks real nice, just waiting for travis to go green.

Should we consider adding more tests for decoding the blosc header? E.g. have something larger that cannot be compressed? (From what I understand, the 4th bit is set because the input data is so small.)

**Comment by esc** [comment]
Travis Python 3.4 segfaulted, re-running travis tests.

**Comment by FrancescElies** [comment]
If I understood correctly yes too, yes. 4th bit is set because data is so small.
I'll add another test for that case too

**Comment by esc** [comment]
Please make a new PR, merging this now to get master green again.

**Comment by esc** [comment]
So awesome! Thanks so much!!

**Comment by esc** [comment]
New release imminent.

**Pull request merged**
