### PR TITLE
migrate from nose to pytest

### PR DESCRIPTION
**Pull request by bnavigator**
The patch from #99

Any plans to make a new release? 0.16 is broken with current numpy.

### CODE REVIEW

**Comment by esc** [comment]
@bnavigator thank you for submitting this. The project has a single developer and zero financial backing so I've not found the time yet to cut a new release. I can't commit to an exact date yet but I do hope to cut a new release "soon".

Let me know when this is ready to be merged and I'll click the button!

**Comment by bnavigator** [comment]
I don't know, I guess you have to fix the unrelated test failures first in order to see if this PR is good.

**Comment by esc** [comment]
Also, I think CI is currently broken... On my wishlist is a migration to GHA

**Comment by bnavigator** [comment]
> On my wishlist is a migration to GHA

Your .travis.yml looks reasonably simple. A really generic GitHub Action workflow show work well.

**Comment by bnavigator** [comment]
> On my wishlist is a migration to GHA

Your wish be granted.

**Comment by esc** [comment]
> > On my wishlist is a migration to GHA
> 
> Your wish be granted.

Thanks, I will now merge this blindly to run GHA and we can then fix the remaining issues on `master`.

**Comment by esc** [comment]
@bnavigator I am not convinced yet, those `yields` are a good idea.

**Comment by esc** [comment]
@bnavigator thank you for getting this unstuck btw!

**Comment by esc** [comment]
@bnavigator do you have a reproducer for 0.16 being broken with Numpy?

**Comment by bnavigator** [comment]
openSUSE package build: 
- https://build.opensuse.org/package/show/home:bnavigator:branches:devel:languages:python:numeric/python-bloscpack
- [bloscpack_0.16-obs_log.txt](https://github.com/Blosc/bloscpack/files/6124464/bloscpack_0.16-obs_log.txt)

remove nose patch applied to tag v0.16:
https://github.com/bnavigator/bloscpack/tree/v0.16-pytest

**Comment by esc** [comment]
@bnavigator i believe the patch from #99 was very buggy. I have fixed the code on master now, can you check it?

**Comment by bnavigator** [comment]
Yes, current master looks good. 
[bloscpack-master.log](https://github.com/Blosc/bloscpack/files/6125182/bloscpack-master.log)

**Pull request merged**
