### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by FrancescElies**
https://github.com/Blosc/bloscpack/pull/63 followup

- Adds a test
- Modifies the array size of the previous test

If I understand correctly 256 items (float32) array is still uncompressible, right?
Which is the minimum length at which it starts to be compressed?

Best

### CODE REVIEW

**Comment by FrancescElies** [comment]
It seems I made a mistake somewhere, I'll have a look later today or tomorrow

**Comment by FrancescElies** [comment]
Travis segmentation fault for py35, is this happening often? I triggered the job one more time

**Comment by esc** [comment]
Perfect!

**Comment by esc** [comment]
Yeah, it segfaults occasionally on travis, apparently.

**Pull request merged**
