### PR TITLE
Unpinned blosc from 1.2.7

### PR DESCRIPTION
**Pull request by oogali**
This in conjunction with https://github.com/Blosc/python-blosc/issues/114 should make all well again.

### CODE REVIEW

**Comment by esc** [comment]
Hmmm, where is travis? You/we are going to have to fix the test-suite too.

**Comment by esc** [comment]
https://travis-ci.org/Blosc/bloscpack/pull_requests <-- your PR should be listed here.

**Comment by esc** [comment]
Anyway, I'm going to merge this now and break master, perhaps that will create some interesting incentives.

**Comment by esc** [comment]
Also, next time, please consider adding an entry to the changelog.

**Comment by esc** [comment]
@oogali do you want commit access, that way you can merge other peoples pull-requests too?

**Comment by oogali** [comment]
@esc Sure. I can give some time to reviewing PRs.

**Pull request merged**
