### PR TITLE
use setuptools for scripts and deps

### PR DESCRIPTION
**Pull request by mindw**
* make script work on win32
* simplify install instructions
* AFAIK pip requires setuptools to be present when installing from source.

### CODE REVIEW

**Comment by esc** [comment]
Hi,

Thanks for you contribution! I have a few points you should address before I can merge this.

I actually tried installing dependencies with ``setup.py`` some time ago but couldn't make it work reliably, because the numpy dependency couldn't be installed. So that is why you can see the weird call to ``wget`` (which will fail on windows).

I tried your solution today and I can't make it work in a virtualenv, which is (I think) the same issue I was having when I tried it.

```
zsh» python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to bloscpack.egg-info/requires.txt
writing bloscpack.egg-info/PKG-INFO
writing top-level names to bloscpack.egg-info/top_level.txt
writing dependency_links to bloscpack.egg-info/dependency_links.txt
writing entry points to bloscpack.egg-info/entry_points.txt
reading manifest file 'bloscpack.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'bloscpack.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/bloscpack
copying build/lib.linux-x86_64-2.7/bloscpack/log.py -> build/bdist.linux-x86_64/egg/bloscpack
copying build/lib.linux-x86_64-2.7/bloscpack/util.py -> build/bdist.linux-x86_64/egg/bloscpack
copying build/lib.linux-x86_64-2.7/bloscpack/append.py -> build/bdist.linux-x86_64/egg/bloscpack
copying build/lib.linux-x86_64-2.7/bloscpack/constants.py -> build/bdist.linux-x86_64/egg/bloscpack
copying build/lib.linux-x86_64-2.7/bloscpack/testutil.py -> build/bdist.linux-x86_64/egg/bloscpack
copying build/lib.linux-x86_64-2.7/bloscpack/args.py -> build/bdist.linux-x86_64/egg/bloscpack
copying build/lib.linux-x86_64-2.7/bloscpack/serializers.py -> build/bdist.linux-x86_64/egg/bloscpack
copying build/lib.linux-x86_64-2.7/bloscpack/exceptions.py -> build/bdist.linux-x86_64/egg/bloscpack
copying build/lib.linux-x86_64-2.7/bloscpack/pretty.py -> build/bdist.linux-x86_64/egg/bloscpack
copying build/lib.linux-x86_64-2.7/bloscpack/__init__.py -> build/bdist.linux-x86_64/egg/bloscpack
copying build/lib.linux-x86_64-2.7/bloscpack/file_io.py -> build/bdist.linux-x86_64/egg/bloscpack
copying build/lib.linux-x86_64-2.7/bloscpack/abstract_objects.py -> build/bdist.linux-x86_64/egg/bloscpack
copying build/lib.linux-x86_64-2.7/bloscpack/version.py -> build/bdist.linux-x86_64/egg/bloscpack
copying build/lib.linux-x86_64-2.7/bloscpack/abstract_io.py -> build/bdist.linux-x86_64/egg/bloscpack
copying build/lib.linux-x86_64-2.7/bloscpack/checksums.py -> build/bdist.linux-x86_64/egg/bloscpack
copying build/lib.linux-x86_64-2.7/bloscpack/cli.py -> build/bdist.linux-x86_64/egg/bloscpack
copying build/lib.linux-x86_64-2.7/bloscpack/headers.py -> build/bdist.linux-x86_64/egg/bloscpack
copying build/lib.linux-x86_64-2.7/bloscpack/defaults.py -> build/bdist.linux-x86_64/egg/bloscpack
copying build/lib.linux-x86_64-2.7/bloscpack/memory_io.py -> build/bdist.linux-x86_64/egg/bloscpack
copying build/lib.linux-x86_64-2.7/bloscpack/sysutil.py -> build/bdist.linux-x86_64/egg/bloscpack
copying build/lib.linux-x86_64-2.7/bloscpack/metacodecs.py -> build/bdist.linux-x86_64/egg/bloscpack
copying build/lib.linux-x86_64-2.7/bloscpack/numpy_io.py -> build/bdist.linux-x86_64/egg/bloscpack
byte-compiling build/bdist.linux-x86_64/egg/bloscpack/log.py to log.pyc
byte-compiling build/bdist.linux-x86_64/egg/bloscpack/util.py to util.pyc
byte-compiling build/bdist.linux-x86_64/egg/bloscpack/append.py to append.pyc
byte-compiling build/bdist.linux-x86_64/egg/bloscpack/constants.py to constants.pyc
byte-compiling build/bdist.linux-x86_64/egg/bloscpack/testutil.py to testutil.pyc
byte-compiling build/bdist.linux-x86_64/egg/bloscpack/args.py to args.pyc
byte-compiling build/bdist.linux-x86_64/egg/bloscpack/serializers.py to serializers.pyc
byte-compiling build/bdist.linux-x86_64/egg/bloscpack/exceptions.py to exceptions.pyc
byte-compiling build/bdist.linux-x86_64/egg/bloscpack/pretty.py to pretty.pyc
byte-compiling build/bdist.linux-x86_64/egg/bloscpack/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/bloscpack/file_io.py to file_io.pyc
byte-compiling build/bdist.linux-x86_64/egg/bloscpack/abstract_objects.py to abstract_objects.pyc
byte-compiling build/bdist.linux-x86_64/egg/bloscpack/version.py to version.pyc
byte-compiling build/bdist.linux-x86_64/egg/bloscpack/abstract_io.py to abstract_io.pyc
byte-compiling build/bdist.linux-x86_64/egg/bloscpack/checksums.py to checksums.pyc
byte-compiling build/bdist.linux-x86_64/egg/bloscpack/cli.py to cli.pyc
byte-compiling build/bdist.linux-x86_64/egg/bloscpack/headers.py to headers.pyc
byte-compiling build/bdist.linux-x86_64/egg/bloscpack/defaults.py to defaults.pyc
byte-compiling build/bdist.linux-x86_64/egg/bloscpack/memory_io.py to memory_io.pyc
byte-compiling build/bdist.linux-x86_64/egg/bloscpack/sysutil.py to sysutil.pyc
byte-compiling build/bdist.linux-x86_64/egg/bloscpack/metacodecs.py to metacodecs.pyc
byte-compiling build/bdist.linux-x86_64/egg/bloscpack/numpy_io.py to numpy_io.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying bloscpack.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying bloscpack.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying bloscpack.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying bloscpack.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying bloscpack.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying bloscpack.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/bloscpack-0.7.2_dev-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing bloscpack-0.7.2_dev-py2.7.egg
removing '/home/esc/virtualenv/blospack/lib/python2.7/site-packages/bloscpack-0.7.2_dev-py2.7.egg' (and everything under it)
creating /home/esc/virtualenv/blospack/lib/python2.7/site-packages/bloscpack-0.7.2_dev-py2.7.egg
Extracting bloscpack-0.7.2_dev-py2.7.egg to /home/esc/virtualenv/blospack/lib/python2.7/site-packages
bloscpack 0.7.2-dev is already the active version in easy-install.pth
Installing blpk script to /home/esc/virtualenv/blospack/bin

Installed /home/esc/virtualenv/blospack/lib/python2.7/site-packages/bloscpack-0.7.2_dev-py2.7.egg
Processing dependencies for bloscpack==0.7.2-dev
Searching for numpy
Reading http://pypi.python.org/simple/numpy/
Best match: numpy 1.9.1
Downloading https://pypi.python.org/packages/source/n/numpy/numpy-1.9.1.zip#md5=223532d8e1bdaff5d30936439701d6e1
Processing numpy-1.9.1.zip
Running numpy-1.9.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ergV8_/numpy-1.9.1/egg-dist-tmp-8Jr1eZ
Running from numpy source directory.
Warning: distutils distribution has been initialized, it may be too late to add a subpackage commandWarning: distutils distribution has been initialized, it may be too late to add a subpackage fcompilernon-existing path in 'numpy/distutils': 'site.cfg'
Warning: distutils distribution has been initialized, it may be too late to add a subpackage distutilsWarning: distutils distribution has been initialized, it may be too late to add a subpackage testingnon-existing path in 'numpy/f2py': 'docs'
non-existing path in 'numpy/f2py': 'f2py.1'
Warning: distutils distribution has been initialized, it may be too late to add a subpackage f2pyWarning: distutils distribution has been initialized, it may be too late to add an extension _dummyWarning: distutils distribution has been initialized, it may be too late to add a library npysortWarning: distutils distribution has been initialized, it may be too late to add an extension multiarrayWarning: distutils distribution has been initialized, it may be too late to add an extension umathWarning: distutils distribution has been initialized, it may be too late to add an extension scalarmath/tmp/easy_install-ergV8_/numpy-1.9.1/numpy/distutils/system_info.py:1526: UserWarning: 
    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  warnings.warn(AtlasNotFoundError.__doc__)
Warning: distutils distribution has been initialized, it may be too late to add an extension _dotblasWarning: distutils distribution has been initialized, it may be too late to add an extension umath_testsWarning: distutils distribution has been initialized, it may be too late to add an extension test_rationalWarning: distutils distribution has been initialized, it may be too late to add an extension struct_ufunc_testWarning: distutils distribution has been initialized, it may be too late to add an extension multiarray_testsWarning: distutils distribution has been initialized, it may be too late to add an extension operand_flag_testsWarning: distutils distribution has been initialized, it may be too late to add a subpackage coreWarning: distutils distribution has been initialized, it may be too late to add an extension _compiled_basenon-existing path in 'numpy/lib': 'benchmarks'
Warning: distutils distribution has been initialized, it may be too late to add a subpackage libWarning: distutils distribution has been initialized, it may be too late to add an extension fftpack_liteWarning: distutils distribution has been initialized, it may be too late to add a subpackage fft/tmp/easy_install-ergV8_/numpy-1.9.1/numpy/distutils/system_info.py:1432: UserWarning: 
    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  warnings.warn(AtlasNotFoundError.__doc__)
Warning: distutils distribution has been initialized, it may be too late to add an extension lapack_liteWarning: distutils distribution has been initialized, it may be too late to add an extension _umath_linalgWarning: distutils distribution has been initialized, it may be too late to add a subpackage linalgWarning: distutils distribution has been initialized, it may be too late to add an extension mtrandWarning: distutils distribution has been initialized, it may be too late to add a subpackage randomWarning: distutils distribution has been initialized, it may be too late to add a subpackage maWarning: distutils distribution has been initialized, it may be too late to add a subpackage matrixlibWarning: distutils distribution has been initialized, it may be too late to add a subpackage compatWarning: distutils distribution has been initialized, it may be too late to add a subpackage polynomialWarning: distutils distribution has been initialized, it may be too late to add a subpackage docWarning: distutils distribution has been initialized, it may be too late to add a subpackage numpy_configtest.c:1:5: warning: conflicting types for built-in function ‘exp’ [enabled by default]
_configtest.o: In function `main':
/tmp/easy_install-bZ653E/numpy-1.9.1/_configtest.c:6: undefined reference to `exp'
collect2: error: ld returned 1 exit status
_configtest.o: In function `main':
/tmp/easy_install-bZ653E/numpy-1.9.1/_configtest.c:6: undefined reference to `exp'
collect2: error: ld returned 1 exit status
_configtest.c:1:5: warning: conflicting types for built-in function ‘exp’ [enabled by default]
_configtest.c:1:20: fatal error: Python.h: No such file or directory
compilation terminated.
_configtest.c:1:20: fatal error: Python.h: No such file or directory
compilation terminated.
Traceback (most recent call last):
  File "setup.py", line 50, in <module>
    'Topic :: Utilities',
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/esc/virtualenv/blospack/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/home/esc/virtualenv/blospack/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/install.py", line 101, in do_egg_install
    cmd.run()
  File "/home/esc/virtualenv/blospack/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/easy_install.py", line 349, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/esc/virtualenv/blospack/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/easy_install.py", line 569, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/esc/virtualenv/blospack/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/easy_install.py", line 621, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/esc/virtualenv/blospack/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/easy_install.py", line 673, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/esc/virtualenv/blospack/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 576, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "/home/esc/virtualenv/blospack/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 821, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/home/esc/virtualenv/blospack/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 833, in obtain
    return installer(requirement)
  File "/home/esc/virtualenv/blospack/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/easy_install.py", line 589, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/esc/virtualenv/blospack/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/easy_install.py", line 619, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/esc/virtualenv/blospack/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/easy_install.py", line 809, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/esc/virtualenv/blospack/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/easy_install.py", line 1086, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/esc/virtualenv/blospack/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/easy_install.py", line 1075, in run_setup
    run_setup(setup_script, args)
  File "/home/esc/virtualenv/blospack/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/sandbox.py", line 30, in run_setup
    lambda: execfile(
  File "/home/esc/virtualenv/blospack/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/sandbox.py", line 72, in run
    return func()
  File "/home/esc/virtualenv/blospack/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/sandbox.py", line 32, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 251, in <module>
    
  File "setup.py", line 243, in setup_package
    
  File "/tmp/easy_install-ergV8_/numpy-1.9.1/numpy/distutils/core.py", line 169, in setup
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/esc/virtualenv/blospack/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/bdist_egg.py", line 172, in run
    self.run_command("egg_info")
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/tmp/easy_install-ergV8_/numpy-1.9.1/numpy/distutils/command/egg_info.py", line 10, in run
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/tmp/easy_install-ergV8_/numpy-1.9.1/numpy/distutils/command/build_src.py", line 153, in run
  File "/tmp/easy_install-ergV8_/numpy-1.9.1/numpy/distutils/command/build_src.py", line 170, in build_sources
  File "/tmp/easy_install-ergV8_/numpy-1.9.1/numpy/distutils/command/build_src.py", line 329, in build_extension_sources
  File "/tmp/easy_install-ergV8_/numpy-1.9.1/numpy/distutils/command/build_src.py", line 386, in generate_sources
  File "numpy/core/setup.py", line 432, in generate_config_h
    
  File "numpy/core/setup.py", line 42, in check_types
    classifiers = ['Development Status :: 3 - Alpha',
  File "numpy/core/setup.py", line 293, in check_types
    
SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.
```

Installing numpy using ``pip`` in the same virtualenv works fine. Maybe doing this with something that came from PyPi will work, I don't know.

I addition to that removal of the ``blpk`` script breaks the build, because the ``cram`` command-line tests can not be run. Last time I checked, only doing an ``install`` would generate the entry-points and there is no way to generate this into the source tree, but maybe that has changed?

Also, I really dislike duplicating the requirements into two different places, the ``setup.py`` and the ``requirements.txt`. If the issues above can be solved, maybe you could read the requirements from the ``requirements.txt`` in the ``setup.py`` to avoid unnecessary duplication.

**Comment by esc** [comment]
For more issues trying to install numpy like above see:

https://github.com/pydata/numexpr/issues/143

https://stackoverflow.com/questions/21605927/why-doesnt-setup-requires-work-properly-for-numpy

**Comment by mindw** [comment]
I keep forgetting that. I'll fix this soon soon enough,

**Comment by esc** [comment]
If you can manage to put all the dependencies in ``setup.py`` and make the solution work reliably, I'd be delighted!

**Comment by mindw** [comment]
Please note that the above error is caused by missing packages - as noted by the log :
```
SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.
```

**Comment by esc** [comment]
Yes, I thought so too, but then why does ``pip install numpy`` succeed?

**Comment by esc** [comment]
Okay, so it seems the ``Python.h`` is found by pip in ``/usr/include/python2.7`` which is the system Python.

**Comment by esc** [comment]
Not sure what the deal is with the drop in coverage, maybe some of the coverage generated by cram is missing, not too important though.

**Comment by esc** [comment]
an example of reading the requirements files:

https://github.com/pydata/numexpr/blob/master/setup.py#L27

**Comment by mindw** [comment]
re-using requirement files for package metadata is not recommended:
https://caremad.io/2013/07/setup-vs-requirement/

**Comment by mindw** [comment]
cram does not seem to be very portable. Maybe scripttest (https://github.com/pypa/scripttest) is a better choice ...

**Comment by esc** [comment]
Any idea why the coverage dropped? I can't reproduce, because the changes break being able to run this locally.

**Comment by esc** [comment]
The error I get is:

```
   $ blpk compress data.dat
+  /bin/sh: 12: run: not found
+  [127]
   $ ls
   data.dat
-  data.dat.blp
```

**Comment by esc** [comment]
The low coverage is because the coverage from the cram cli tests isn't being included:

```
bloscpack.cli                  217    129    41%   85, 109-111, 131-143, 147-153, 157-162, 167-169, 174-175, 188-195, 198, 201, 265-268, 291-305, 428-521
```

**Comment by esc** [comment]
I saw you managed to get coverage back up by not deleting the ``blpk`` script. Maybe you could make a commit sausage when doing this kind of experimental stuff and only squash commits before I merge the pull-request? That way I could follow what you are trying and avoid duplicating efforts. :star:

**Comment by esc** [comment]
I actually though it might be to do with the ``.coveragerc`` file which I needed during the early days of coveralls, but removing it didn't help:

https://travis-ci.org/esc/bloscpack/jobs/51884466

**Comment by mindw** [comment]
It was mostly trial and error. Travis did not report report the "after_success" action has failed (forgot to add coveralls to requirements.txt). While at it I cleaned up some more stuff.
In any case installations works on Travis and on my Linux test system (Fedora 20).

**Comment by esc** [comment]
You want to leave it like it is?

**Comment by mindw** [comment]
What is the current state?

**Comment by esc** [comment]
I think it is fine like this, will be merged today, sorry for the delay.

**Comment by esc** [comment]
closed via 6e9edcade6d3a8b737cdcacd78ba93a7c67f5109

**Comment by esc** [comment]
Thanks again for this, works like a charm with version '0.7.2'!

**Comment by mindw** [comment]
My pleasure :)

**Comment by esc** [comment]
If you want to, have time and inclination, Bcolz could probably do with a closer look at the setup.py: https://github.com/Blosc/bcolz :-D

**Pull request closed without merging**
